sonar.projectKey=NaukriAutomator
   sonar.projectName=NaukriAutomator
   sonar.sourceEncoding=UTF-8

   sonar.sources=backend/src/main,mock-naukri/src/main,frontend/src,electron
   sonar.tests=backend/src/test,mock-naukri/src/test

   sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/build/**,**/electron/resources/**

   sonar.java.binaries=backend/target/classes,mock-naukri/target/classes
