server:
  port: 0
  address: 127.0.0.1
spring:
  application:
    name: naukri-be
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    root: INFO
    com.adi.naukri: DEBUG
